---
- name: install golang from tarball
  become: true
  block:
    - name: erase old go
      ansible.builtin.file:
        state: absent
        path: /usr/local/go
    - name: install new go
      ansible.builtin.command:
        cmd: >
          tar -C /usr/local -xzf /usr/local/src/go{{ golang_version }}.tar.gz
