---
apiVersion: v1
kind: Service
metadata:
  name: krb5
  namespace: it
spec:
  selector:
    app: krb5
  ports:
    - name: kerberos
      protocol: TCP
      port: 88
      targetPort: 88
    - name: kpasswd
      protocol: TCP
      port: 464
      targetPort: 464
    - name: kerberos-admin
      protocol: TCP
      port: 749
      targetPort: 749
  type: LoadBalancer
  loadBalancerIP: 10.11.0.12
