---
- name: common binary packages
  ansible.builtin.package:
    state: latest
    name:
      - curl
      - git
      - "lua{{ lua_minor_version}}"   # for nvim configuration
      - "liblua{{ lua_minor_version}}-dev"   # for nvim configuration
      - lsd
      - python3-pip
      - wget
      - zsh
- name: language support packages
  ansible.builtin.package:
    state: latest
    name:
      - jq
      - lld
      - npm   # required for npm packages
      - pipx  # required for language support on neovim
