---
apiVersion: v1
kind: Service
metadata:
  name: ldap
  namespace: it
spec:
  selector:
    app: ldap
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 389
  type: LoadBalancer
