---
- hosts: linux
  roles:
    - role: common
    - role: user_gmc 
- hosts: development
  roles:
    - role: development
- hosts: netcontrol
  roles:
    - role: timeserver
    - role: nameserver
- hosts: access_server
  roles:
    - role: access_server
    - role: nameserver
