---
# Binary packages should be installed first
- name: Languages and language support packages
  ansible.builtin.package:
    state: latest
    name:
      - docker
      - jq
      - lld
      - npm   # required for npm packages
      - pipx
      - python3.11
      - python3.11-venv
      - python3-invoke
      - ruby
      - wget
      - zsh
