---
named:
  contact: gmc
  expire: 604800
  negative_cache_ttl: 86400
  refresh: 86400
  retry: 28800
  serial: 2024121301
  ttl: 86400
  v6: false
  subnets:
    - netid: 68
      hosts:
        goemon: 73
        goliath: 74
        jigen: 75 
        zantetsuken: 76
        argocd: 21
        awx: 21
        gitlab: 21
        harbor: 21
        mtl-lba: 21
        vault: 21
        mtl-printer: 61
        ns1: 31
        krb: 13
        ldap: 14
        ca: 15
        ns: 31
        ns2: 32
        portainer: 14
        rpi1: 31
        rpi2: 32
        rpi3: 33
        rpi4: 34
    - netid: 73
      hosts:
        fujiko: 12
        knw-ha: 41
        knw-jump: 42
        knw-access: 43
        knw-printer: 61
        ns3: 31
  canonical:
    argocd: jigen.cummings-online.local.
    awx: jigen.cummings-online.local.
    ingress: jigen.cummings-online.local.
    netbox: jigen.cummings-online.local.
    prometheus: jigen.cummings-online.local.
    time: rpi1.cummings-online.local.

