dictionaries = ["en_gb"]
words = [
    "analyzer",
    "ansible",
    "ansiblels",
    "autoindent",
    "autopairs",
    "autoread",
    "autosession",
    "autotag",
    "bashls",
    "bibtex",
    "bufnr",
    "cmake",
    "cmakelint",
    "colorcolumn",
    "commentstring",
    "completeopt",
    "cssls",
    "cursorline",
    "cwd",
    "decremental",
    "dockerls",
    "expandtab",
    "fileencoding",
    "fileformat",
    "fzf",
    "gitcommit",
    "glyphs",
    "gmc",
    "gomod",
    "gopls",
    "gosum",
    "hls",
    "hlsearch",
    "ignorecase",
    "incsearch",
    "integrations",
    "isort",
    "josean",
    "jsonlint",
    "jsonls",
    "jsregexp",
    "keybinds",
    "keymap",
    "keymaps",
    "lspkind",
    "luadoc",
    "lualine",
    "luasnip",
    "makefiles",
    "mapleader",
    "markdownlint",
    "maximizer",
    "maxwidth",
    "menuone",
    "monokai",
    "neovim",
    "netrw",
    "nginx",
    "noselect",
    "nvim",
    "oldfiles",
    "parsers",
    "pydocstyle",
    "pyright",
    "rstcheck",
    "scrolloff",
    "shiftwidth",
    "signcolumn",
    "smartcase",
    "softtabstop",
    "splitbelow",
    "splitright",
    "stylua",
    "systemdlint",
    "tabclose",
    "tabn",
    "tabnew",
    "tabp",
    "tabstop",
    "termguicolors",
    "terraformls",
    "timeoutlen",
    "tmux",
    "unnamedplus",
    "vimdoc",
    "vscode",
    "yamllint",
    "yamlls",
]
