---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.io/loadBalancerIPs: 10.11.0.31
  name: bind9
  namespace: it
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  selector:
    app: bind9
  ports:
    - port: 53
      name: domainudp
      targetPort: 53
      protocol: UDP
    - port: 53
      name: domaintcp
      targetPort: 53
      protocol: TCP
