---
# Binary packages should be installed first
- name: Languages and language support packages
  ansible.builtin.package:
    state: latest
    name:
      # - docker
      - python3.12
      - python3.12-venv
      - python3-invoke
      - ruby
