---
# Binary packages should be installed first
- name: Languages and language support packages
  ansible.builtin.package:
    state: latest
    name:
      - docker
      - python3.11
      - python3.11-venv
      - python3-invoke
      - ruby
